swagger: "2.0"

info:
  title: "CGMViz Flask backend"
  version: "0.1"

basePath: /v1.0

paths:
  /items:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
