branch-defaults:
  vueFrontEnd:
    environment: cgmflask-env
    group_suffix: null
environment-defaults:
  cgmFlask-dev:
    branch: null
    repository: null
  cgmflask-env:
    branch: null
    repository: null
global:
  application_name: cgmFlask
  branch: null
  default_ec2_keyname: cgmFlask
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
